spring.application.name=Transcribe-Server

# url
server.port=5001

# log
logging.level.root=info
logging.level.com.hanzo.transcribeserver=debug

# transcribe server url
transcribe.server.url=http://localhost:5001

# api ? ?? ???
spring.config.import=optional:application-private.properties